import Foundation

/// Ordered list of words that have been generated by Claude and are awaiting
/// the speaker. `highlightIndex` tracks the alignment cursor; words at or above
/// it have not been spoken yet.
public final class PromptBuffer {
    public private(set) var words: [String] = []
    public private(set) var highlightIndex: Int = 0

    public init() {}

    public func reset() {
        words.removeAll()
        highlightIndex = 0
    }

    public func append(_ token: String) {
        words.append(token)
    }

    public func append(contentsOf tokens: [String]) {
        words.append(contentsOf: tokens)
    }

    public func advance(to index: Int) {
        highlightIndex = max(highlightIndex, min(index, words.count))
    }

    public var remainingWords: Int { max(0, words.count - highlightIndex) }
    public var unspoken: ArraySlice<String> { words[highlightIndex...] }
    public var spoken: ArraySlice<String> { words[..<highlightIndex] }

    /// The words to feed to TTS that haven't been queued yet.
    /// Caller tracks its own TTS queue cursor.
    public func newWords(since lastIndex: Int) -> ArraySlice<String> {
        guard lastIndex < words.count else { return [] }
        return words[lastIndex..<words.count]
    }
}
